### ISSUE TITLE
clique

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#10]
<img src="https://arasatasaygin.github.io/openlogos/logos/clique.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/clique-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by marcog83** [comment]
Hi, the project I'd like to apply is named "RoboJS".

https://github.com/marcog83/RoboJS

RoboJS is a library that aims to dynamically load JS modules depending on how the DOM is composed. Add a node to the DOM and a JS will be loaded! Remove a node and the JS will be disposed!! Not further framework frontend , but a tool that lets you manage the association DOM and JS in less than 4k gzipped

**Comment by arasatasaygin** [comment]
Hey @marcog83 
You are the first claimer of openlogos. Thanks for the support :)

**Comment by aroberge** [comment]
Hi,

Thank you for this opportunity to claim one of your logos for free!

I have multiple projects in the **Reeborg's World** family and I'd like to claim this logo for one of them - with the hope to eventually add related logos to the other projects in this family.

https://github.com/aroberge/reeborg is a the main project: a Karel-the-robot implementation that can be programmed using either Python or Javascript, or using a blockly interface.  The main site where it lives is http://reeborg.ca/reeborg.html.   (The live site is currently not available through https.)  The entire project is available in both French and English, and partially available in Polish and Korean - with work on additional languages being currently done by volunteers.

https://github.com/aroberge/reeborg-staging is a staging version used for testing or for those that want absolute privacy as it is available as a secure site https://aroberge.github.io/reeborg-staging/

https://github.com/aroberge/reeborg-docs is a tutorial for learning programming using Reeborg's World. The tutorial is currently available in French, English and Korean, with additional languages in the works.

https://github.com/aroberge/reeborg-howto is a site aimed at creators of advanced tasks for Reeborg's World. It has very little content currently but will have more to be migrated from https://github.com/aroberge/reeborg-world-creation which was written as an online book (a format which I found to be unsatisfactory.)

https://github.com/aroberge/reeborg-dist is for those interested in installing their own version of Reeborg's World by simply unzipping a file, instead of cloning a repository with unnecessary files.

https://github.com/aroberge/reeborg-api is a documentation site for the API that creators of advanced tasks can use.

**Comment by blakeembrey** [comment]
This is a really awesome initiative @arasatasaygin!

I'd like to apply the logo to https://github.com/serviejs. Currently I'm using an icon from https://thenounproject.com. ServieJS is an organisation I started working on last year when I started using AWS lambda and have slowly been building up, but have yet to do any full announcement of the project. It's designed to abstract HTTP away from core JavaScript libraries so the same interfaces are working over XHR (with https://github.com/serviejs/popsicle), HTTP (with https://github.com/serviejs/servie-http) and AWS Lambda (with https://github.com/serviejs/servie-lambda), but can be expanded to many others (e.g. `popsicle` works with HTTP2 and HTTP1 in node.js - the first library to automatically support HTTP2 upgrades in node.js that I know of).

**Comment by arasatasaygin** [comment]
Both reeborg and serviejs looks great. Thanks for claiming @blakeembrey @aroberge

**Comment by vchrombie** [comment]
Hi @arasatasaygin 
I would like to claim this logo for one of my projects, https://github.com/vchrombie/scorpion-hut.github.io

I am actually building this website for my friend's robot, _paripreksya_, which is a multi-terrain rescue robot. The site is under construction and I am looking for a nice logo and happened to your repository. The clique logo suits this project as it is a robot information site and the structure of our bot looks same except for one extra arm in the logo compared to the robot. 

You can have a look at the photos of the robot from here scorpion-hut.github.io/

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/clique-guide.jpg">

Congrats @marcog83         
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone.
Cheers

~ Aras

**Comment by jmintb** [comment]
@marcog83 as far as I can tell the logo was never put into use. If you are not using it, can I use it instead? :)
