### ISSUE TITLE
the-fall

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#18]
<img src="https://arasatasaygin.github.io/openlogos/logos/the-fall.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/the-fall-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by DrRoach** [comment]
Hello, second and last submission. 

[DynamicImage](https://gitlab.com/DrRoach/DynamicImage) is a web server based image generation project that generates dynamically sized images on the fly.

Imagine you have a user account system where users upload profile pictures. You then want these profile pictures to be displayed in either `128x128`, `512x512` or `1024x1024` depending on how the picture is being displayed. Well rather than having to create these three images when the image is first uploaded, using DynamicImage they can be created on the fly using the original uploaded image from the user. This allows you much greater flexibility in the future if you ever decide to introduce `256x256` images and if no image can be found, your `no_image.jpg` can be returned as part of the project.

DynamicImage includes built in caching and image invalidation on update along with support for multiple image types including GIFs and more.

**Comment by sid77** [comment]
Hello,
[drop](https://github.com/sid77/drop) is a library that provides an easy way for dropping privileges in Go. The library takes care of calling the right combination of `setre{s}[g,u]id()` syscalls depending on the platform the program is being built for.

**Comment by jhpratt** [comment]
[r/Spacex Mission Control](https://github.com/r-spacex/mission-control) is a web-based application to host launch threads on r/SpaceX. Currently, its usage is relatively limited, but I am currently working on a bottom-up rewrite that will provide a combined interface with live updates, push notifications, and integrated streaming (potentially chat as well). It will have everything people will want to know about a launch while it's happening, and I expect it to have thousands (or tens of thousands) of users during each launch.

I chose this icon because it resembles an asteroid, reminding people of space.

**Comment by christhekeele** [comment]
Hey there! :wave:

[Mnemonix](https://github.com/christhekeele/mnemonix) is an open-source interface to key-value stores for the BEAM VM. It allows Elixir and erlang programmers to write the same code everywhere, while changing the underlying backend through configuration. It's intended for for developers who have different memory needs in different environments (in-memory in dev/test, redis in prod), are assessing what benefits switching off their current store might get them (easy to benchmark different engines), or interested in composing multiple backends to build a bespoke layered caching system (read-through, write-through, you name it).

I'm excited to say I'm close to releasing v1.0.0! I'm on that last 10% stretch: better [docs](https://hexdocs.pm/mnemonix/Mnemonix.html), more tests, low-hanging optimization fruit. I've had to work on it in fits and spurts but I have set aside time this summer to take it over the finish line, it'd be brilliant to release with a logo!

It was hard to choose just one logo to request for this project—many have great depictions of animals associated with memory or knowledge—but ultimately settled on this one which evokes Mnemonix lifting the burden from a relieved mind.

**Comment by arasatasaygin** [comment]
Hello everyone, great projects. Thanks for claiming this logo.
@DrRoach we are using small_light at work but I'm not sure if your project is 100% similar. Good work.
@sid77 name/logo fit 👍
@jhpratt very exciting project. Every time I watch a launch, it gives me goosebumps.
@christhekeele good luck with v1.0.0.
Cheers.

**Comment by DrRoach** [comment]
@arasatasaygin what small_light library is it that you use? Would be interested to take a look 😄 I'm yet to find a project yet that can be thrown onto a webserver and left to it's own devices (the whole DynamicImage aims to fill) but thank you I appreciate the comments 👍

**Comment by arasatasaygin** [comment]
@DrRoach https://github.com/cubicdaiya/ngx_small_light is the module we are using for nginx.

**Comment by kdrag0n** [comment]
Hello!

I'd like to claim this logo for my Android device kernels under the name of Velocity Kernel. My kernels improve the performance and battery life of devices. So far, I have made Velocity for two devices (one is a collaboration). Links:

- [S8 XDA](https://forum.xda-developers.com/galaxy-s8/samsung-galaxy-s8--s8-cross-device-development/kernel-s8-linaro-velocity-kernel-r1-t3801924)
- [S8 GitHub](https://github.com/kdrag0n/velocity_dream)
- [A1 XDA](https://forum.xda-developers.com/mi-a1/development/kernel-mi-a1-treble-clang-velocity-t3795032)
- [A1 GitHub](https://github.com/kdrag0n/velocity_tissot)

Cheers!

**Comment by DrRoach** [comment]
@arasatasaygin Thanks for the link. There's certainly a lot more functionality baked into that project, hopefully I'll get some of the features that they have working in Dynamic Image over the weekend 🤞 The main difference with that project though is that it's an ngix module. Dynamic Image is a simple PHP library that can be hosted on any server and then used to serve images on the fly. I like the idea of the image modifications that they have though!! +1

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/the-fall-guide.jpg">

Congrats @DrRoach  
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
