### ISSUE TITLE
mr-jumbo

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#2]
<img src="https://arasatasaygin.github.io/openlogos/logos/mr-jumbo.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/mr-jumbo-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by NikolaGavric94** [comment]
Hello @arasatasaygin and other fellow developers,

I would like to post my claim on this logo here for the currently 2 open source projects under https://github.com/NikolaGavric94 which hardly focus on the different payment gateway implementations for `Laravel` that are not present in the current (Laravel Cashier)[https://github.com/laravel/cashier] project.

I think this logo would fit the current and upcoming projects because of the official PHP logo which is also an Elephant and since the `Laravel` is PHP framework it would be a perfect fit.

**[laravel-square](https://github.com/NikolaGavric94/laravel-square)** project focuses on Square Connect V2 implementation with Laravel along with the use of Square Customer and Square Order Vault systems. This will be extended in the future to cover more of Square Vault systems. The library handles all of the Customers, Orders, Transactions, Taxes, Discounts, etc. for you (developer) and gives you intuitive ways of charging your customers.

**[nikolag-core](https://github.com/NikolaGavric94/nikolag-core)** project focuses on a core building block of future payment gateway implementations and gives you a set of already predefined migrations, services and other things to get you quickly started with writing your own library for the above purpose.

For the future I will be bringing in a code generator tool which will help you generate all of the scaffolding code `(models, migrations, controllers, routes, form requests with policies)` for your `Laravel/Lumen` projects in the future and it will be highly customizable, just like above 2 projects.

I plan on creating more libraries which can help developers with handling all the boring and time demanding tasks to a bare minimum effort required to setup and use.

**I wish you all good coding and may sessions always be with you!**

**Comment by Nuttymoon** [comment]
Hi everyone!
I would like to claim "mr jumbo" logo for my project which is actually called... **[Jumbo](https://github.com/adaltas/jumbo)**!
Jumbo is a CLI tool written in Python that allows to quickly deploy virtualized Hadoop clusters locally. We developed it with a friend during our internship.

I think the logo is a great match with Jumbo for these reasons:
- It looks fun and friendly, as I hope Jumbo is. We targeted developers with low knowledge of Hadoop to help them build a development environment very easily;
- Hadoop logo is also an elephant;
- The fun fact that the logo and our project share the same name!
 
The project is in its early days and lots of features are yet to come.

Anyway, giving away your logos to developers is awesome @arasatasaygin, thank you for that!

**Comment by arasatasaygin** [comment]
Hey everyone many thanks for the kind words.
@NikolaGavric94 your projects look great.
@schmidyy it's great that you choose to commit on OS, cheers.
@Nuttymoon I really liked your project and what a great coincidence on the name :)

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/jumbo-guide.jpg">

Congrats @Nuttymoon  
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again everyone for claiming and supporting.
Cheers

~ Aras
