### ISSUE TITLE
apple

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#23]
<img src="https://arasatasaygin.github.io/openlogos/logos/apple.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/apple-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by Bromind** [comment]
Hey @arasatasaygin, 
This logo would perfectly fit a small pomodoro timer I wrote few weeks ago. I've been looking here a few time to see if someone would ask for it, but it doesn't seem to be the case. So [here it is](https://framagit.org/Bromind/i3-pomodoro). Nothing fancy.
Anyway, my project is pretty small, so if someone else is interested in the logo, I'd be glad to withdraw my claim :-)

Just a more explaination on my program: it is a pomodoro timer. In a word, a pomodoro timer is used to stay focus on a task you have to do. You set a timer for (e.g.) 15 minutes, and during this time, you only think on your task. When the timer is over, you can proceed to the next task. With a bit of training, it becomes quite easy to schedule a work program, e.g. 3 × 15 min work, then 15 minutes break, etc.

This method is called pomodoro because people use to have timers which look like tomatos (pomodoro in Italian if I'm not mistaken). Though your logo is intended to be an apple, it also looks like a tomato (except for the leaf).

In my timer, when the time is over, a notification is sent (using libnotify) with a tomato logo and the task title. In its current state, the logo I use one I found randomly, but it would be nice to have a dedicated one.

Anyway, thanks for the work you did, that's awesome :-)

**Comment by garrettw** [comment]
@Bromind you need to add a license file to your project to show that it is indeed open-source.

**Comment by Bromind** [comment]
Whoops, you're right. It's so obvious to me that I didn't even though about it.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/apple-guide.jpg">

Congrats @Bromind  Tomatoes are the new apples :)
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone.
Cheers

~ Aras

**Comment by Abserial** [comment]
Is this a reference to the headache meme
