### ISSUE TITLE
ferdinand

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#26]
<img src="https://arasatasaygin.github.io/openlogos/logos/ferdinand.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/ferdinand-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by Mineirovsky** [comment]
**[divboy](https://github.com/Mineirovsky/divboy)** is a step sequencer for Gameboy Advance in early development, I'd like to have this logo for it.
Thanks

**Comment by arasatasaygin** [comment]
Thanks for claiming this logo @Mineirovsky divboy looks great. Cheers.

**Comment by arpandesai** [comment]
Is it already claimed?

**Comment by arasatasaygin** [comment]
@arpandesai you can claim it as well.

Every logo has one github issue that you can introduce your project to and claim.
Community can upvote your comment and you can upvote other projects as well under these issues.
Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by garrettw** [comment]
I wouldn't mind using this for the IRC bot library I'm developing, called [Pierce](https://github.com/garrettw/pierce). Part of my idea behind the name has to do with my library competing with [Phergie](https://www.phergie.org/) -- they're both object-oriented PHP libraries, but mine is a male name to contrast with the other's female name.
(I know I haven't made a commit in a while, but that's because I've only recently started working on it again, and I'm working on a big piece of functionality that I don't want to commit until it actually works.)
