### ISSUE TITLE
gate-keeper

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#3]
<img src="https://arasatasaygin.github.io/openlogos/logos/gate-keeper.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/gate-keeper-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by filipekiss** [comment]
First of all, thank you for this, @arasatasaygin! Open Source design for logos is not something we see everyday and I think that if more designers contributed to open-source we could have software that's beautiful AND free!

That said, I'd like to claim the Gate Keeper logo for my [zshero] project. I'm still working on it, but it's on a usable pre-release already and, since I use it on my personal dotfiles, the idea is to keep updating zshero for a long time!

#### About Zshero

Zshero is an open-source configuration manager written in ZSH to be fast and easy to use. It adds a function to your interactive shell that allows you to easily manage configuration files (also known as dotfiles) without too much trouble. Just tell zshero what do you want to version and it will take care of the rest!

[zshero]: https://github.com/filipekiss/zshero

**Comment by sarveswaran-m** [comment]
@arasatasaygin Much appreciate your work and the idea of awarding the logos to open-source projects.

Gatekeeper would make an appropriate log for [blockingMap4j.](https://github.com/sarveswaran-m/blockingMap4j) 

**About BlockingMap4j**
Blocking map acts as a key-based synchronizer between producers and consumers in concurrent environment. It is a Map that additionally supports operations that wait for a key to be available when retrieving an element. There can be multiple producers populating & multiple consumers consuming from the same blocking map. BlockingMap is thread-safe & highly-concurrent.

Since blockingmap acts like a gatekeeper between producer and consumers, the gatekeeper logo would make a good logo for the project.

**Comment by dafei1288** [comment]
Hey @arasatasaygin so great of you to do so .  And I believe that you can help many developers . 

May I claim this logo for my [Max](https://github.com/dafei1288/max) !

**About max**
The name is from《Two Broke Girls》. One of the heroines , Max . 
Her goal is to help junior developers use lambda in Java.  And she also contains powerful computing functions. 

Thank you so much.

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/gate-keeper-guide.jpg">

Congrats @filipekiss    
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone.
Cheers

~ Aras
