### ISSUE TITLE
hangry-birds

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/openlogos#5]
<img src="https://arasatasaygin.github.io/openlogos/logos/hangry-birds.jpg" width="325" height="325"><img src="https://arasatasaygin.github.io/openlogos/logos/hangry-birds-o.jpg" width="325" height="325">

## To claim this logo
* Introduce your active open source project.
* Community can upvote your comment and you can upvote other projects as well.
* Starting from 1st of July, I will give one logo per day until the end of month according to these upvotes.

**Comment by DrRoach** [comment]
Hello, the project that I would like to put forward is called [NetworkAPI](https://gitlab.com/DrRoach/NetworkAPI).

It is a Java networking library/API to make long drawn out networking processes quick and simple. It will allow relatively new/novice Java programmers to implement Server/Client architectures in their programs with just a few lines of code. Whether that's communication between desktops, mobiles or tablets. As long as it runs Java they will all be able to talk to each other.

Whether you use NetworkAPI for messaging apps, backend game communication or just a simple mobile app no changes other than initial setup are needed other than the boilerplate setup and method overloads. This being said, the library isn't just for new developers but for everybody that's fed up of implementing the whole networking structure project after project.

NetworkAPI leverages threads so that performance is optimal and latency is kept to an absolute minimum.

Also included in this library will be end-end encryption and server signature verification so that people can feel assured that whatever data they are sending won't be able to be intercepted and read by third parties. This is a major talking point right now around the globe with people becoming more concerned about their privacy and what information may be in third party hands.

**Comment by moinism** [comment]
I'd like to request this one for BotUI: https://github.com/botui/botui

Its a framework to create conversational UIs.

I liked the `Clique` but that's already gone so this makes sense as the birds and can be interpreted as different parties in the chat/messages.

**Comment by arasatasaygin** [comment]
Hey, many thanks for your kind words.

@DrRoach None of us have enough time to work on our projects I guess. It took me months to release this one. NetworkAPI looks good btw.
@moinism  Liked botui. I actually needed something like this, thanks. You can claim clique if you want, it is still there.

**Comment by DrRoach** [comment]
@arasatasaygin Thank you, appreciate it 👊

**Comment by BhautikChudasama** [comment]
I want to this for my chat web app.

**Comment by garrettw** [comment]
@BhautikChudasama you have to provide a link to your open-source project

**Comment by moinism** [comment]
@arasatasaygin have you started awarding the logos yet?

**Comment by jwu910** [comment]
@moinism if you follow his repository, you can see when the logos have been awarded. There hasn't been much other activity so its not a lot of spam

**Comment by arasatasaygin** [comment]
<img src="https://openlogos.org/logos/hangry-birds-guide.jpg">

Congrats @moinism     
Can you please get in touch with me from arasatasaygin-at-gmail.com. I'll share all resource files, fonts, and sticker mule voucher.

Thanks again for claiming and supporting everyone.
Cheers

~ Aras
